name: Cryptomator
on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * *'

permissions:
  # Required for add-and-commit
  contents: write

jobs:
  cryptomator-version-check:
    runs-on: ubuntu-latest
    outputs:
      newVersionNumber: ${{ steps.latest-release.outputs.result }}
      oldVersionNumber: ${{ steps.current-version.outputs.version }}
      hasNewerVersion: ${{ steps.has-newer-version.outputs.hasNewerVersion }}
      exeSha: ${{ steps.generate-sha.outputs.exeSha }}
    steps:
      - uses: actions/checkout@v2
      - name: Get current cryptomator version
        id: current-version
        run: |
          echo ::set-output name=version::$(python ./scripts/get_nuspec_verison.py ./packages/cryptomator/cryptomator.nuspec)
      - uses: actions/github-script@v6
        id: latest-release
        with:
          script: |
            const scripts = require('./scripts/release.js');
            return await scripts.latestRelease({github, context}, 'cryptomator', 'cryptomator');
          result-encoding: string
      - name: Compare versions
        id: has-newer-version
        run: |
          echo ::set-output name=hasNewerVersion::$(python ./scripts/has_newer_version.py "${{steps.current-version.outputs.version}}" "${{steps.latest-release.outputs.result}}")
      - name: Get download url (failure means no .msi file in release)
        id: download-url
        if: ${{ steps.has-newer-version.outputs.hasNewerVersion == 'true' }}
        uses: actions/github-script@v6
        with:
          script: |
            const scripts = require('./scripts/release.js');
            return await scripts.latestReleaseUrl({github, context}, 'cryptomator', 'cryptomator', 'x64.msi');
          result-encoding: string
      - name: Generate a sha256 checksum for the download
        id: generate-sha
        if: ${{ steps.has-newer-version.outputs.hasNewerVersion == 'true' }}
        run: |
          wget -O new.exe ${{ steps.download-url.outputs.result }}
          echo "::set-output name=exeSha::$(sha256sum new.exe | awk '{ print $1}')"

  cryptomator-update:
    runs-on: windows-latest
    needs:
      - cryptomator-version-check
    if: ${{ needs.cryptomator-version-check.outputs.hasNewerVersion == 'true' }}
    steps:
      - uses: actions/checkout@v2
      - name: Update files
        run: .\packages\cryptomator\scripts\update_version.ps1 ${{ needs.cryptomator-version-check.outputs.oldVersionNumber }} ${{ needs.cryptomator-version-check.outputs.newVersionNumber }} ${{ needs.cryptomator-version-check.outputs.exeSha }}
        shell: pwsh
      - name: Pack
        shell: pwsh
        run: cd packages/cryptomator; choco pack
      - name: Push
        shell: pwsh
        run: cd packages/cryptomator; choco push --api-key ${{ secrets.CHOCOLATEY_API_KEY }}
      - name: Commit changes back to the repository
        uses: EndBug/add-and-commit@v8
        with:
          branch: master
          message: Cryptomator ${{ needs.cryptomator-version-check.outputs.newVersionNumber }}
